### ISSUE TITLE
node-build may not contain newer node versions

### ISSUE THREAD

**Issue by gnawhleinad** [github/homebrew-bootstrap#34]
... and the traditional `script/bootstrap` won't upgrade `node-build`.

For example, using

>```
>  brew update >/dev/null
>  brew bundle check &>/dev/null || brew bundle
>
>  brew bootstrap-rbenv-ruby
>  brew bootstrap-nodenv-node
>```

So, if a developer who has `node-build 2.3.6` will not have `node-6.9.1` listed in `node-build --definitions`. Or, using the above `bootstrap` example, it will fail with

>```
> Error: cannot find Node  definition!
>```

/cc: @gjtorikian, @bwestover, @zacharysarah

**Comment by MikeMcQuaid** [comment]
The listed commands will update `node-build` to the latest version if `node-build` is in the `Brewfile`. If not, I suspect someone hit https://github.com/homebrew/brew#update-bug.
