### ISSUE TITLE
Getting a 401 because of 2FA?

### ISSUE THREAD

**Issue by rmosolgo** [github/homebrew-bootstrap#46]
Hi! 👋  

I'm getting back to my dev environment after some long leave, but having a bit of trouble with `script/bootstrap`, which seems to trace back to this library's `brew-report-issue.rb` script. 

Here's what I get from `script/bootstrap`: 

```
  # Lots of missing migrations 
  20180103182342 DropBillingTransactionEntries
  20180103223316 RunBackfillOrgProjectAbilitiesTransition
Run `rake db:migrate` to update your database then try again.
error: database or repo setup failed for dotcom environment.
================================================================================
All done! Your current environment: GitHub dotcom on Ruby 2.4.3-p200
Username for 'https://github.com': rmosolgo
Password for 'https://rmosolgo@github.com':
Error: failed to get issues (https://api.github.com/repos/github/github-bootstrap-failures/issues?creator=rmosolgo)!
--
401: Must specify two-factor authentication OTP code.
Error: your GitHub username/access token are not correct! Fix by running Strap:
  https://strap.githubapp.com
```

(I think this message comes from [here](https://github.com/github/homebrew-bootstrap/blob/master/cmd/brew-report-issue.rb#L87-L92).)

I got a new `strap.sh` and ran it, and it was successful, but I get the same error from `script/bootstrap`.

I can double-check the credentials by running this in `irb`: 

```ruby
def credential_helper(command, input)
   IO.popen({"RUBYLIB" => nil, "RUBYOPT" => nil},
            ["git", "credential", "#{command}"], "w+") do |io|
     io.puts input
     io.close_write
     io.read
   end
end
@github_credentials = credential_helper :fill, "protocol=https\nhost=github.com"

puts @github_credentials
# protocol=https
# host=github.com
# username=rmosolgo
# password=<my-actual-password>
```

I double-checked the password by using it to sign into an incognito window. 

It seems like the GitHub API is [behaving as documented](https://developer.github.com/v3/auth/#working-with-two-factor-authentication), asking for a one-time password. 

Can you help me work through this, or suggest another place to look? Sorry, I'm sure I botched some local config, but I _really_ don't know where to look next 😖  ! 

Thanks! 

cc @MikeMcQuaid  as the contact in the Readme

**Comment by mistydemeo** [comment]
Can you try running this:

```
$ git credential reject
```

Then rerun strap? It should create a new entry for you by creating a new oauth token and filling it in as the password. If that doesn't work, we can look into other options.

**Comment by rmosolgo** [comment]
Thanks for your suggestion, it works! 

I ran: 

```
$ git credential reject 
host=github.com 

$ 
```

Then re-ran strap, and now, when I check my credentials, I _don't_ see my real password. Instead, I see an auth token. `script/bootstrap` finishes just fine.

I learned a thing about our tooling and now it works 😊  Thank you!
