### ISSUE TITLE
brew-upgrade-mysql assumes jq dependency

### ISSUE THREAD

**Issue by phillmv** [github/homebrew-bootstrap#57]
Hey!,

Heads up, brew-upgrade-mysql failed on my box because it assumed `jq` was preinstalled :).

Not sure where you'd fix this but just putting it out there.
https://github.com/github/homebrew-bootstrap/blob/3381a20bf779477d81fb402ec1e40bc97b596bb6/cmd/brew-upgrade-mysql#L26

Cheers,

**Comment by rlinehan** [comment]
`script/bootstrap` on my machine is giving me a warning about this too, although not failing

```
vendor/homebrew-bootstrap/cmd/brew-upgrade-mysql: line 26: jq: command not found
```

**Comment by tomkrouper** [comment]
In the meantime
```
brew install jq
```
manually then running will fix it. I'll try to fix this by doing a `brew install` inside the script unless folks think that is a bad idea.

**Comment by phillmv** [comment]
Was putting it in a brewfile just not gonna work? My only observation is dependency manifest files lead to less long term pain ;).

Otherwise :+1:, looks dealt with to me.
