### ISSUE TITLE
bootstrap-rbenv-ruby fails on Ruby 2.2.4 because of 'gem install bundler'

### ISSUE THREAD

**Issue by gyfis** [github/homebrew-bootstrap#68]
When running `brew bootstrap-rbenv-ruby` with `ruby-2.2.4`, it fails because of the `gem install bundler` step, since the newest `bundler` is not compatible with Ruby 2.2.4. Not sure if that's expected since Ruby 2.2.4 is already after its end-of-life date.

Log output:
```
Installed ruby-2.2.4 to /Users/xxx/.rbenv/versions/2.2.4

Fetching: bundler-2.0.1.gem (100%)
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
Error: brew-bootstrap-rbenv-ruby failed!
```

**Comment by mistydemeo** [comment]
Good catch - I'll see about fixing this.
