### ISSUE TITLE
bootstrap-rbenv-ruby does not respect RBENV_ROOT

### ISSUE THREAD

**Issue by jasonkarns** [github/homebrew-bootstrap#80]
`bootstrap-rbenv-ruby` doesn't seem to respect RBENV_ROOT.

I have rbenv installed and RBENV_ROOT configured to a custom location. The ruby version requested by the app (hookshot, in this case) _is_ installed to RBENV_ROOT but is not being respected (thanks to the `--skip-existing` flag https://github.com/github/homebrew-bootstrap/blob/791a4078dda719fe9f333b9664c3d4417bf920e8/cmd/brew-bootstrap-rbenv-ruby#L84)

So a reinstall of the ruby version is forced, but it installs the ruby to ~/.rbenv instead of $RBENV_ROOT. After the ruby installation is complete, that version is not detectable or usable by rbenv.

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry!
